### ISSUE TITLE
error in command [p]google

### ISSUE THREAD

**Issue by greymattt** [npc203/npc-cogs#59]
- command ran:
**[p]google helo**
```py
[ERROR] red: Exception in command 'google'
Traceback (most recent call last):
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/aravind/Library/Application Support/Red-DiscordBot/data/netav/cogs/CogManager/cogs/google/google.py", line 92, in google
    await ResultMenu(source=Source(pages, per_page=1)).start(ctx)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 948, in start
    await super().start(ctx, channel=channel, wait=wait)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 688, in start
    self.message = msg = await self.send_initial_message(ctx, channel)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 944, in send_initial_message
    return await channel.send(**kwargs)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/abc.py", line 890, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/utils.py", line 318, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type URL is not JSON serializable
```
**[p]google image latest waifus**
```py
[ERROR] red: Exception in command 'google image'
Traceback (most recent call last):
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/aravind/Library/Application Support/Red-DiscordBot/data/netav/cogs/CogManager/cogs/google/google.py", line 304, in image
    await ResultMenu(source=ImgSource(response, per_page=1)).start(ctx)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 948, in start
    await super().start(ctx, channel=channel, wait=wait)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 688, in start
    self.message = msg = await self.send_initial_message(ctx, channel)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/redbot/vendored/discord/ext/menus/__init__.py", line 944, in send_initial_message
    return await channel.send(**kwargs)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/abc.py", line 890, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "/Users/aravind/opt/anaconda3/lib/python3.9/site-packages/discord/utils.py", line 318, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aravind/opt/anaconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type URL is not JSON serializable
```
other commands seems to work well

**Comment by npc203** [comment]
A one time issue, closing this, stale now.
