### ISSUE TITLE
[BUG] Embed logic will show more than 25 fields.

### ISSUE THREAD

**Issue by DJTOMATO** [npc203/npc-cogs#76]
Chelp is showing more than 25 fields in a embed causing it to crash help commands.
This is on dpy2 branch

https://cdn.discordapp.com/attachments/914905365701853214/1191579684018860122/Screenshot_2024-01-02-00-12-01-801_com.discord.jpg?ex=65af2e8f&is=659cb98f&hm=1342d3005b45b17af9747dcc866c08de3a956862ab47889c91527cbba0a0157d&

https://cdn.discordapp.com/attachments/914905365701853214/1191589253898055750/image.png?ex=65af3778&is=659cc278&hm=e7df05dda4ae5c417cb6be2e54733f88d3c02738cda2358c3d2e210ffd311095&

```py
[2023-12-30 03:25:20] [ERROR] red: Exception in command 'help'
Traceback (most recent call last):
  File "/home/glas/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glas/redenv/lib/python3.11/site-packages/redbot/core/commands/help.py", line 925, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for, from_help_command=True)
  File "/home/glas/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1288, in send_help_for
    return await self._help_formatter.send_help(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/customhelp/core/base_help.py", line 166, in send_help
    await self.format_category_help(ctx, help_for, help_settings=help_settings)
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/customhelp/themes/danny.py", line 86, in format_category_help
    await self.send_pages(
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/customhelp/core/base_help.py", line 498, in send_pages
    await menu.start(ctx)
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/customhelp/core/base_help.py", line 577, in start
    await self.menus[1].start(ctx)
  File "/mnt/hdd/data/lenabot/cogs/CogManager/cogs/customhelp/core/views.py", line 124, in start
    self.message = await ctx.send(
                   ^^^^^^^^^^^^^^^
  File "/home/glas/redenv/lib/python3.11/site-packages/redbot/core/commands/context.py", line 91, in send
    return await super().send(content=content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glas/redenv/lib/python3.11/site-packages/discord/ext/commands/context.py", line 1024, in send
    return await super().send(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/glas/redenv/lib/python3.11/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/glas/redenv/lib/python3.11/site-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields: Must be 25 or fewer in length.```

**Comment by DJTOMATO** [comment]
Temporal fix is just remove cogs from that category until you have 24 or less.
